// <auto-generated />
namespace TP5Samourai.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class samourai1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(samourai1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009211420578_samourai1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
